#!/bin/bash
########################################################################
#
# hsrsync
#
########################################################################

########################################################################
# vars

DSTDIR="${HOME}/Dropbox/HSR"
MNTDIR="${HOME}/.hsrsync"
SRCDIRS="${MNTDIR}/Informatik/Fachbereich/Engineering-Projekt/EPJ \
  ${MNTDIR}/Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1 \
  ${MNTDIR}/Informatik/Fachbereich/Parallele_Programmierung/ParProg \
  ${MNTDIR}/Informatik/Fachbereich/Web_Engineering_+_Design_1/WED1"

########################################################################
# user input

echo -n "User: "
read USERNAME

echo -n "Password: "
read -s PASS

echo

########################################################################
# preparation

if ! [ -d "${MNTDIR}" ]; then
  echo -n "creating ${MNTDIR}... "
  mkdir "${MNTDIR}"
  echo "[ OK ]"
fi

if ! [ -d "${DSTDIR}" ]; then
  echo "[ ERROR ]"
  echo "${DSTDIR} doesn't exist!"
  exit 1
fi

########################################################################
# mounting

rawurlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    # You can either set a return variable (FASTER) 
  REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
}

SMBPASS=$( rawurlencode "$PASS" )

if ! mount | grep "on ${MNTDIR}" > /dev/null; then
  echo -n "mounting hsr folder to ${MNTDIR}... "
  mount_smbfs "//${USERNAME}:${SMBPASS}@hsr.ch/root/alg/skripte" "${MNTDIR}"
  if ! mount | grep "on ${MNTDIR}" > /dev/null; then
    echo "[ ERROR ]"
    echo "Error while mounting ${MNTDIR}!"
    exit 1
  else
    echo "[ OK ]"
  fi
fi

########################################################################
# syncing files

for SRCDIR in ${SRCDIRS}; do
  SUBJECTNAME=$(basename ${SRCDIR})
  mkdir -p "${DSTDIR}/${SUBJECTNAME}/skripte"

  rsync -ahz --progress --delete \
    --exclude "*.lnk" \
    --exclude "Desktop.ini" \
    --exclude "Thumbs.db" \
    --exclude ".DS_Store" \
    "${SRCDIR}/" "${DSTDIR}/${SUBJECTNAME}/skripte"
done

########################################################################
# unmounting

echo -n "unmounting ${MNTDIR}... "
if umount "${MNTDIR}" >/dev/null 2>&1
then
  echo "[ OK ]"
  rmdir "${MNTDIR}"
  echo
else
  echo "[ ERROR ]"
fi

########################################################################
# final output

echo total size:
du -hs "${DSTDIR}"
