#!/bin/bash
########################################################################
#
# hsrsync
#
########################################################################

########################################################################
# vars

DSTDIR="${HOME}/Dropbox/HSR/var/skripts"
MNTDIR="${HOME}/.hsrsync"
SRCDIR="${MNTDIR}/Informatik/Fachbereich/Algorithmen_und_Datenstrukturen_2/AD2 \
  ${MNTDIR}/Informatik/Fachbereich/Informations-_und_Codierungstheorie/ICTh \
  ${MNTDIR}/Informatik/Fachbereich/Computernetze_1/CN1 \
  ${MNTDIR}/Informatik/Fachbereich/Computernetze_1/CN1Prak \
  ${MNTDIR}/Informatik/Fachbereich/Software-Engineering_1/SE1 \
  ${MNTDIR}/Informatik/Fachbereich/C++/CPl"
VPNTESTDOMAIN="skripte.hsr.ch"
VPNHOST="vpn.hsr.ch"

########################################################################
# user input

echo -n "User: "
read USERNAME

echo -n "Password: "
read -s PASS

echo ""

########################################################################
# vpn

if [[ ! $(dig +short "${VPNTESTDOMAIN}" | head -1) == *"hsr.ch"* ]]
then
  echo "[ INFO ] not in hsr network"
  sleep 2
  echo -e "connect to vpn... "
  echo "${PASS}" | sudo openconnect --passwd-on-stdin -u "${USERNAME}" "${VPNHOST}" > /dev/null &
  sleep 5
  if [[ $(dig +short "${VPNTESTDOMAIN}" | head -1) == *"hsr.ch"* ]]
  then
    VPN_USAGE=true
    echo "[ OK ]"
  else
    echo "[ ERROR ]"
    echo "vpn connection error"
    exit 1
  fi
fi


########################################################################
# preparation

if ! [ -d "${MNTDIR}" ]
then
  echo -n "creating ${MNTDIR}... "
  mkdir "${MNTDIR}"
  echo "[ OK ]"
fi

if ! [ -d "${DSTDIR}" ]
then
  echo "[ ERROR ]"
  echo "${DSTDIR} doesn't exist!"
  exit 1
fi

########################################################################
# mounting

if ! mount | grep "on ${MNTDIR}" > /dev/null; then
  echo -n "mounting hsr folder to ${MNTDIR}... "
  mount_smbfs "//${USERNAME}:${PASS}@hsr.ch/root/alg/skripte" "${MNTDIR}"
  if ! mount | grep "on ${MNTDIR}" > /dev/null; then
    echo "[ ERROR ]"
    echo "Error while mounting ${MNTDIR}!"
    exit 1
  else
    echo "[ OK ]"
  fi
fi

########################################################################
# syncing files

rsync -ahz --progress --delete \
  --exclude "*.lnk" \
  --exclude "Desktop.ini" \
  --exclude "Thumbs.db" \
  --exclude ".DS_Store" \
  --exclude "CompB/HS_201[23]" \
  --exclude "ICTh/Unterlagen 2014/Videos*" \
  ${SRCDIR} "${DSTDIR}"

########################################################################
# unmounting

echo -n "unmounting ${MNTDIR}... "
if umount "${MNTDIR}" >/dev/null 2>&1
then
  echo "[ OK ]"
  rmdir "${MNTDIR}"
  echo
  if [ "$VPN_USAGE" = true ]; then
    echo "[ INFO ] ending vpn connection"
    sudo kill -SIGTERM %1
  fi
else
  echo "[ ERROR ]"
fi

########################################################################
# final output

echo total size:
du -hs "${DSTDIR}"
